import Example from '@components/Example/Example';
import Head from 'next/head';
import * as React from 'react';

interface Props {
  props: any;
}

export default function Home({ props }: Props) {
  const [count, setCount] = React.useState();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Example />
      <main />
      <footer />
    </div>
  );
}
